[package]
name = "asm-rust"
description = "Assembler for the FCVM virtual machine"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
phf = { version = "0.11.3", features = ["macros"] }
