#include "cpu_instr_descs.h"

static const cpu_instr_desc_t cpu_instr_descs[256] = {
    [CPU_OP_MOV_VR] = {CPU_OP_MOV_VR, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_MOV_RR] = {CPU_OP_MOV_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_STR_RV0] = {CPU_OP_STR_RV0, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_STR_RI0] = {CPU_OP_STR_RI0, 1, {CPU_OPD_REGS}},
    [CPU_OP_STR_RI8] = {CPU_OP_STR_RI8, 2, {CPU_OPD_REGS, CPU_OPD_IMM8}},
    [CPU_OP_STR_RI32] = {CPU_OP_STR_RI32, 2, {CPU_OPD_REGS, CPU_OPD_IMM32}},
    [CPU_OP_STR_RIR] = {CPU_OP_STR_RIR, 2, {CPU_OPD_REGS, CPU_OPD_REG}},
    [CPU_OP_LDR_RV0] = {CPU_OP_LDR_RV0, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_LDR_RI0] = {CPU_OP_LDR_RI0, 1, {CPU_OPD_REGS}},
    [CPU_OP_LDR_RI8] = {CPU_OP_LDR_RI8, 2, {CPU_OPD_REGS, CPU_OPD_IMM8}},
    [CPU_OP_LDR_RI32] = {CPU_OP_LDR_RI32, 2, {CPU_OPD_REGS, CPU_OPD_IMM32}},
    [CPU_OP_LDR_RIR] = {CPU_OP_LDR_RIR, 2, {CPU_OPD_REGS, CPU_OPD_REG}},

    [CPU_OP_ADD_RR] = {CPU_OP_ADD_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_ADD_RV] = {CPU_OP_ADD_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_SUB_RR] = {CPU_OP_SUB_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_SUB_RV] = {CPU_OP_SUB_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_MUL_RR] = {CPU_OP_MUL_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_MUL_RV] = {CPU_OP_MUL_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_DIV_RR] = {CPU_OP_DIV_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_DIV_RV] = {CPU_OP_DIV_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_IDIV_RR] = {CPU_OP_IDIV_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_IDIV_RV] = {CPU_OP_IDIV_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_AND_RR] = {CPU_OP_AND_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_AND_RV] = {CPU_OP_AND_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_OR_RR] = {CPU_OP_OR_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_OR_RV] = {CPU_OP_OR_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_XOR_RR] = {CPU_OP_XOR_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_XOR_RV] = {CPU_OP_XOR_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},
    [CPU_OP_NOT_R] = {CPU_OP_NOT_R, 1, {CPU_OPD_REG}},
    [CPU_OP_SHL_RR] = {CPU_OP_SHL_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_SHL_RV] = {CPU_OP_SHL_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM5}},
    [CPU_OP_SHR_RR] = {CPU_OP_SHR_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_SHR_RV] = {CPU_OP_SHR_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM5}},
    [CPU_OP_ROR_RR] = {CPU_OP_ROR_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_ROR_RV] = {CPU_OP_ROR_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM5}},
    [CPU_OP_ROL_RR] = {CPU_OP_ROL_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_ROL_RV] = {CPU_OP_ROL_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM5}},
    [CPU_OP_CMP_RR] = {CPU_OP_CMP_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_TST_RR] = {CPU_OP_TST_RR, 1, {CPU_OPD_REGS}},
    [CPU_OP_TST_RV] = {CPU_OP_TST_RV, 2, {CPU_OPD_REG, CPU_OPD_IMM32}},

    [CPU_OP_JMPR_V8] = {CPU_OP_JMPR_V8, 1, {CPU_OPD_IMM8}},
    [CPU_OP_JMPA_V32] = {CPU_OP_JMPA_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_JMPA_R] = {CPU_OP_JMPA_R, 1, {CPU_OPD_REG}},
    [CPU_OP_JEQR_V8] = {CPU_OP_JEQR_V8, 1, {CPU_OPD_IMM8}},
    [CPU_OP_JEQA_V32] = {CPU_OP_JEQA_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_JEQA_R] = {CPU_OP_JEQA_R, 1, {CPU_OPD_REG}},
    [CPU_OP_JNER_V8] = {CPU_OP_JNER_V8, 1, {CPU_OPD_IMM8}},
    [CPU_OP_JNEA_V32] = {CPU_OP_JNEA_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_JNEA_R] = {CPU_OP_JNEA_R, 1, {CPU_OPD_REG}},
    [CPU_OP_JGTR_V8] = {CPU_OP_JGTR_V8, 1, {CPU_OPD_IMM8}},
    [CPU_OP_JGTA_V32] = {CPU_OP_JGTA_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_JGTA_R] = {CPU_OP_JGTA_R, 1, {CPU_OPD_REG}},
    [CPU_OP_JGER_V8] = {CPU_OP_JGER_V8, 1, {CPU_OPD_IMM8}},
    [CPU_OP_JGEA_V32] = {CPU_OP_JGEA_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_JGEA_R] = {CPU_OP_JGEA_R, 1, {CPU_OPD_REG}},
    [CPU_OP_JLTR_V8] = {CPU_OP_JLTR_V8, 1, {CPU_OPD_IMM8}},
    [CPU_OP_JLTA_V32] = {CPU_OP_JLTA_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_JLTA_R] = {CPU_OP_JLTA_R, 1, {CPU_OPD_REG}},
    [CPU_OP_JLER_V8] = {CPU_OP_JLER_V8, 1, {CPU_OPD_IMM8}},
    [CPU_OP_JLEA_V32] = {CPU_OP_JLEA_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_JLEA_R] = {CPU_OP_JLEA_R, 1, {CPU_OPD_REG}},
    [CPU_OP_CALLA_V32] = {CPU_OP_CALLA_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_CALLA_R] = {CPU_OP_CALLA_R, 1, {CPU_OPD_REG}},
    [CPU_OP_RET] = {CPU_OP_RET, 0, {}},

    [CPU_OP_PUSH_V32] = {CPU_OP_PUSH_V32, 1, {CPU_OPD_IMM32}},
    [CPU_OP_PUSH_R] = {CPU_OP_PUSH_R, 1, {CPU_OPD_REG}},
    [CPU_OP_POP_R] = {CPU_OP_POP_R, 1, {CPU_OPD_REG}},

    [CPU_OP_NOP] = {CPU_OP_NOP, 0, {}},
    [CPU_OP_HALT] = {CPU_OP_HALT, 0, {}},
    [CPU_OP_INT_V8] = {CPU_OP_INT_V8, 1, {CPU_OPD_IMM8}},
    [CPU_OP_IRET] = {CPU_OP_IRET, 0, {}},
};

const cpu_instr_desc_t *cpu_lookup_instr_desc(uint8_t opcode) {
    const cpu_instr_desc_t *desc = &cpu_instr_descs[opcode];
    // Treat opcode 0x00 in the LUT as a missing descriptor.
    if (desc->opcode == 0) {
        return NULL;
    } else {
        return desc;
    }
}
